cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    rbriggs:
        email: rbriggs@gmail.com
        failed_login_attempts: 0
        first_name: Rebecca
        last_name: Briggs
        logged_in: false
        password: $2b$12$uNaTgvGPG9rMbzOJHYaPQePw0DUfp1qHBrSq6l4O304qani6pKFpm